version: "3.0"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'Postgres2020!'
    ports:
      - '15432:5432'
    volumes:
      - PostgreSQLData:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    ports:
      - '8080:80'
    depends_on:
      - postgres
volumes:
  PostgreSQLData: