version: "3"
services:
    web:
        build: .
        ports:
            - "8000:80"
        depends_on:
            - db-server
    db-server:
        image: microsoft/mssql-server-linux
        container_name: db-server
        environment:
          - ACCEPT_EULA=Y
          - MSSQL_SA_PASSWORD=password123
          - MSSQL_TCP_PORT=1433

        ports:
          - "1400:1433"